services:
  control:
    container_name: control
    build:
      context: .
      dockerfile: dockerfile
    runtime: nvidia
    volumes:
      - ${PROJECT_DIRECTORY_PATH}:/FL_system
      - ${DATA_DIRECTORY_PATH}:/FL_system/data/raw
    environment:
      - PROJECT_DIRECTORY_PATH
      - DATA_DIRECTORY_PATH
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
